"""
benches.py — benchmark families for sweep to iterate over

Single source of truth for the sweep axes, read by cli.py (which hands a
`Bench` to sweep.py) and by the Makefile through a generated axes.mk, produced
from the `make_var` names below with:

    python3 -m tracecliff axes --make > axes.mk

Adding a benchmark family means adding a Bench here and a subparser in cli.py.
Adding a new value to an axis here builds the new binaries and sweeps them.
"""

from tracecliff.sweep import Axis, Bench

# ---------------------------------------------------------------------------
# addr — indirect call / address-packet stress (src/bench_addr.c)
# ---------------------------------------------------------------------------

# N_TARGETS: 1 target = baseline (same address every call, best compression);
#            3+ targets is past the ETM's 3-slot exact-match address history,
#            forcing a real address packet on every call.
ADDR_N_LIST = [1, 2, 3, 4, 8, 16, 32, 64]
# STUB_STRIDE: byte spacing between stub targets, 0 (compiler packing) to a page.
ADDR_STRIDE_LIST = [0, 64, 128, 256, 512, 1024, 2048, 4096]
# ITERS: run length, swept to find the shortest run that is in steady state,
# with and without ETR.
ITERS_LIST = [100_000, 1_000_000, 10_000_000, 100_000_000]

# Two build modes of the same source, differing only in binary name.
ADDR_BENCH_SUBDIR = {"loop": "bin/addr_loop", "chain": "bin/addr_chain"}
ADDR_BIN_PREFIX = {"loop": "bench", "chain": "bench_chain"}


def addr_bench(kind: str) -> Bench:
    """The addr Bench for --kind loop / chain."""
    prefix = ADDR_BIN_PREFIX[kind]
    return Bench(
        name=f"addr_{kind}",
        axes=(
            Axis("n_targets", "n", ADDR_N_LIST, make_var="ADDR_N_LIST"),
            Axis("spacing", "s", ADDR_STRIDE_LIST, make_var="ADDR_STRIDE_LIST"),
            Axis("iters", "iters", ITERS_LIST, width=10, make_var="ITERS_LIST"),
        ),
        binary_name=lambda p: f"{prefix}_n{p[0]}_s{p[1]}_i{p[2]}",
        # one printed block per N_TARGETS, i.e. the whole STUB_STRIDE x ITERS grid
        group_depth=1,
        detail=f"{kind} ({prefix})",
    )


# Every Bench, for the axes emitter.
ALL_BENCHES = (addr_bench("loop"), addr_bench("chain"))


# ---------------------------------------------------------------------------
# Makefile emission
# ---------------------------------------------------------------------------


def make_vars() -> dict[str, list[int]]:
    """Every axis keyed by its Makefile variable name; shared variables must agree."""
    out: dict[str, list[int]] = {}
    for bench in ALL_BENCHES:
        for axis in bench.axes:
            if not axis.make_var:
                continue
            previous = out.setdefault(axis.make_var, axis.values)
            if previous != axis.values:
                raise ValueError(
                    f"{axis.make_var} declared twice with different values: "
                    f"{previous} vs {axis.values}"
                )
    return out


def emit_make() -> str:
    """axes.mk: the sweep axes as Make variables, included by the Makefile."""
    width = max(len(v) for v in make_vars())
    lines = [
        "# Generated by 'python3 -m tracecliff axes --make', do not edit.",
        "# The axis values live in tracecliff/benches.py, edit them there and",
        "# this file is regenerated by the Makefile on the next build.",
        "",
    ]
    lines += [
        f"{var:<{width}} := {' '.join(str(v) for v in values)}"
        for var, values in make_vars().items()
    ]
    return "\n".join(lines) + "\n"


def add_arguments(parser) -> None:
    parser.add_argument(
        "--make", action="store_true", help="emit the axes as Make variables (axes.mk)"
    )


def run(args) -> None:
    if args.make:
        print(emit_make(), end="")
        return
    for var, values in make_vars().items():
        print(f"{var} = {' '.join(str(v) for v in values)}")
