"""
gen_chain.py — emit a dense indirect-branch stub chain for CoreSight ETM
overflow characterization.

Invoked as a tracecliff subcommand (see tracecliff/cli.py):
    python3 -m tracecliff gen-chain N_TARGETS STUB_STRIDE > chains/chain_nN_sS.S

Each stub t0..t(N-1) unconditionally BRs to its successor, the target is a
build-time constant defined here through a single `adr` and consumed by `br`.
The last stub in the sequence, t(N-1), does a plain RET instead, making one
call to t0 run exactly N_TARGETS hops ("a lap") and then return.
"""

import argparse
import sys


def emit_stub(k: int, n: int, stride: int) -> None:
    if stride:
        print(f"\t.balign {stride}")
    print(f"\t.type t{k}, %function")
    print(f"t{k}:")
    if k == n - 1:
        print("\tret")
    else:
        print(f"\tadr\tx11, t{k + 1}")
        print("\tbr\tx11")
    print(f"\t.size t{k}, . - t{k}")
    print()


def run(n_targets: int, stub_stride: int) -> None:
    if n_targets < 1:
        print("N_TARGETS must be >= 1", file=sys.stderr)
        sys.exit(1)

    print(
        f"// Generated by gen_chain.py — N_TARGETS={n_targets} STUB_STRIDE={stub_stride}"
    )
    print('// One call to t0 runs exactly N_TARGETS hops ("a lap") and returns.')
    print()
    print("\t.text")
    print("\t.global t0")
    print()

    for k in range(n_targets):
        emit_stub(k, n_targets, stub_stride)


def add_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("n_targets", type=int, help="number of stub hops in the chain")
    parser.add_argument(
        "stub_stride",
        type=int,
        help="byte alignment between stub targets (0 = default packing)",
    )


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    add_arguments(parser)
    args = parser.parse_args(argv)
    run(args.n_targets, args.stub_stride)
